apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: matishaikh77/frontend_image:latest
        ports:
        - containerPort: 1222
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-episode-01
spec:
  type: NodePort
  selector:
    app: frontend-episode-01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80