apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-classroom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-classroom
  template:
    metadata:
      labels:
        app: backend-classroom
    spec:
      containers:
      - name: backend
        image: matishaikh77/1222-backend-image-classroom:latest
        ports:
        - containerPort: 32221
      volumes:
        - name: database-volume-01
          persistentVolumeClaim:
            claimName: db-claim-01
---
apiVersion: v1
kind: Service
metadata:
  name: backend-classroom
spec:
  selector:
    app: backend-classroom
  ports:
    - protocol: TCP
      port: 32221
      targetPort: 32221